blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="home"),
    path("user/<str:username>/", views.UserPostListView.as_view(), name="user-posts"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/<int:pk>/update/", views.PostUpdateView.as_view(), name="update"),
    path("post/<int:pk>/delete/", views.PostDeleteView.as_view(), name="delete"),
    path("post/new/", views.PostCreateView.as_view(), name="create"),
    path("about/", views.about, name="about"),
]

socialmedia/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users import views as user_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    # Accounts
    path("register/", user_view.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("profile/", user_view.profile, name="profile"),
    # password reset
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Post(models.Model):
    title = models.CharField(_("Post Title"), max_length=100)
    content = models.TextField(_("Post Content"))
    date_posted = models.DateTimeField(_("Post Created At"), default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        if len(self.title) < 30:
            return self.title
        else:
            return f"{self.title[:30]}..."

    def get_absolute_url(self):
        return reverse("blog:post-detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} Profile"

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email"]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]

blog/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Post


class PostListView(ListView):
    model = Post
    template_name = "blog/home.html"
    context_object_name = "posts"
    ordering = ["-date_posted"]
    paginate_by = 5


class UserPostListView(ListView):
    model = Post
    template_name = "blog/user_posts.html"
    context_object_name = "posts"
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get("username"))
        return Post.objects.filter(author=user).order_by("-date_posted")


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ["title", "content"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ["title", "content"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = "/"

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, "blog/about.html", {"title": "about"})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(
                request, f"Your account has been created! You are now able to log in"
            )
            return redirect("login")
    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", {"form": form})


@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Your account has been updated!")
            return redirect("profile")
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {"u_form": u_form, "p_form": p_form}

    return render(request, "users/profile.html", context)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}


{% block content %}
	<h1>Blog About Page</h1>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href={% static 'blog/main.css' %}>

	{% if title %}
		<title>Django Blog - {{ title }}</title>
	{% else %}
		<title>Django Blog</title>
	{% endif %}
</head>

<body>
	<!-- navigation -->
	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
			<div class="container">
				<a class="navbar-brand mr-4" href="/">Django Blog</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
					aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse d-flex justify-content-between" id="navbarToggle">
					<div class="navbar-nav mr-auto">
						<a class="nav-item nav-link {% if request.path == '/' %} fw-bold text-white {% endif %}" href={% url 'blog:home' %}>Home</a>
						<a class="nav-item nav-link {% if request.path == '/about/' %} fw-bold text-white {% endif %}" href={% url 'blog:about' %}>About</a>
					</div>
					<!-- Navbar Right Side -->
					<div class="navbar-nav">
						{% if user.is_authenticated %}
							<a class="nav-item nav-link btn btn-outline-info mx-1" href={% url 'blog:create' %}>New Post</a>
							<a class="nav-item nav-link btn btn-outline-dark mx-1" href={% url 'profile' %}>Profile</a>
							<a class="nav-item nav-link btn btn-outline-danger mx-1" href={% url 'logout' %}>Logout</a>
						{% else %}
							<a class="nav-item nav-link btn btn-outline-dark mx-1" href={% url 'login' %}>Login</a>
							<a class="nav-item nav-link btn btn-outline-dark mx-1" href={% url 'register' %}>Register</a>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>
	</header>
	<!-- ./navigation -->

	<!-- main -->
	<main role="main" class="container">
		<div class="row">
			<div class="col-md-8">
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert-{{ message.tags }}">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}
				{% block content %}{% endblock content %}
			</div>
			<div class="col-md-4">
				<div class="content-section">
					<h3>Our Sidebar</h3>
					<p class='text-muted'>You can put any information here you'd like.
					<ul class="list-group">
						<li class="list-group-item list-group-item-light">Latest Posts</li>
						<li class="list-group-item list-group-item-light">Announcements</li>
						<li class="list-group-item list-group-item-light">Calendars</li>
						<li class="list-group-item list-group-item-light">etc</li>
					</ul>
					</p>
				</div>
			</div>
		</div>
	</main>
	<!-- ./main -->


	<!-- Option 1: Bootstrap Bundle with Popper -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
		integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
		integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
		crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %} 
    {% for post in posts %}
        <article class="media content-section d-flex align-items-center">
            <img src={{ post.author.profile.image.url }} alt={{ post.author.username }} class="rounded-circle article-img" />
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href={% url 'blog:user-posts' post.author.username %}>{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href={% url 'blog:post-detail' post.pk %}>{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %} 
    <!-- Pagination -->
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
                <div class="form-group mt-2">
                    <button type="submit" class="btn btn-outline-danger">Yes, Delete</button>
                    <a class="btn btn-outline-secondary" href={% url 'blog:post-detail' object.pk %}>Cancel</a>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %} 
    <article class="media content-section d-flex align-items-center">
        <img src={{ object.author.profile.image.url }} alt={{ object.author.username }} class="rounded-circle article-img" />
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href={% url 'blog:user-posts' object.author.username %}>{{ object.author.username }}</a>
                <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
                {% if object.author == user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href={% url 'blog:update' object.pk %}>Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href={% url 'blog:delete' object.pk %}>Delete</a>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
        </div>
    </article>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
                <div class="form-group mt-2">
                    <button type="submit" class="btn btn-outline-info">Post</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}

{% block content %} 
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section d-flex align-items-center">
            <img src={{ post.author.profile.image.url }} alt={{ post.author.username }} class="rounded-circle article-img" />
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href={% url 'blog:user-posts' post.author.username %}>{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href={% url 'blog:detail' post.pk %}>{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %} 
    <!-- Pagination -->
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}

users/templates/users/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
                <div class="form-group mt-3">
                    <button type="submit" class="btn btn-outline-info">Sign In</button>
                    <small class="text-muted ml-2"><a href={% url 'password_reset' %}>Forgot Password?</a></small>
                </div>
            </fieldset>
        </form>

        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a href={% url 'register' %} class="ml-2">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'blog/base.html' %}


{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href={% url 'login' %}>Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
                <div class="form-group mt-3">
                    <button type="submit" class="btn btn-outline-info">Request Password Reset</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends 'blog/base.html' %}


{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href={% url 'login' %}>Sign In Here</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
                <div class="form-group mt-3">
                    <button type="submit" class="btn btn-outline-info">Reset Password</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'blog/base.html' %}


{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password.
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="content-section">
        <div class="media d-flex align-items-center">
            <img class="rounded-circle account-img" src={{ user.profile.image.url }}>
            <div class="media-body flex-start">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>

        <!-- FORM HERE -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
                <div class="form-group mt-3">
                    <button type="submit" class="btn btn-outline-info">Update</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-info">Sign Up</button>
                </div>
            </fieldset>
        </form>

        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a href={% url 'login' %} class="ml-2">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}